INSERT INTO dim_proveedores (id_proveedor, nombre_empresa, pais_origen, moneda_compra, dias_credito, nivel_servicio) VALUES 
(1, 'Shenzhen Global Tech', 'China', 'USD', 30, 'Premium'),
(2, 'Berlin Tech Logistics', 'Alemania', 'EUR', 45, 'Estandar'),
(3, 'Austin Components', 'USA', 'USD', 15, 'Critico'),
(4, 'Tokyo Precision', 'Japón', 'JPY', 60, 'Premium'),
(5, 'Seoul Semiconductor', 'Corea del Sur', 'KRW', 30, 'Premium'),
(6, 'Lyon Industrial Systems', 'Francia', 'EUR', 45, 'Estandar'),
(7, 'Milan Parts & Co', 'Italia', 'EUR', 30, 'Estandar'),
(8, 'Toronto Hardware', 'Canadá', 'CAD', 30, 'Estandar'),
(9, 'Sao Paulo Mfg', 'Brasil', 'BRL', 15, 'Critico'),
(10, 'Taiwan Semi Corp', 'Taiwán', 'USD', 15, 'Premium'),
(11, 'Vietnam Assembly Plant', 'Vietnam', 'USD', 45, 'Critico'),
(12, 'Bangalore IT Solutions', 'India', 'INR', 60, 'Estandar'),
(13, 'London Instruments', 'Reino Unido', 'GBP', 30, 'Premium'),
(14, 'Madrid Global Supply', 'España', 'EUR', 45, 'Estandar'),
(15, 'Chicago Heavy Machinery', 'USA', 'USD', 15, 'Critico'),
(16, 'Shanghai Express Mfg', 'China', 'USD', 30, 'Estandar'),
(17, 'Singapore Smart Tech', 'Singapur', 'USD', 30, 'Premium'),
(18, 'Tel Aviv Security', 'Israel', 'ILS', 30, 'Premium'),
(19, 'Amsterdam Logistics', 'Países Bajos', 'EUR', 60, 'Estandar'),
(20, 'Stockholm Solutions', 'Suecia', 'SEK', 45, 'Estandar'),
(21, 'Guangzhou Optics', 'China', 'USD', 45, 'Estandar'),
(22, 'Munich Motors', 'Alemania', 'EUR', 30, 'Premium'),
(23, 'Silicon Valley Inc', 'USA', 'USD', 0, 'Premium'), -- Pago de contado
(24, 'Osaka Precision Tools', 'Japón', 'JPY', 45, 'Estandar'),
(25, 'Bangalore Tech Park', 'India', 'USD', 30, 'Critico'),
(26, 'Kuala Lumpur Circuits', 'Malasia', 'MYR', 30, 'Estandar'),
(27, 'Zurich Fine Parts', 'Suiza', 'CHF', 60, 'Premium'),
(28, 'Dublin Data Systems', 'Irlanda', 'EUR', 30, 'Estandar'),
(29, 'Warsaw Assembly', 'Polonia', 'PLN', 45, 'Estandar'),
(30, 'Istanbul Logistics', 'Turquía', 'TRY', 30, 'Critico'),
(31, 'Sydney Hardware Group', 'Australia', 'AUD', 45, 'Estandar'),
(32, 'Brussels Chemicals', 'Bélgica', 'EUR', 30, 'Estandar'),
(33, 'Bangkok Electronics', 'Tailandia', 'THB', 45, 'Critico'),
(34, 'Copenhagen Design', 'Dinamarca', 'DKK', 60, 'Premium'),
(35, 'Helsinki Networks', 'Finlandia', 'EUR', 45, 'Estandar'),
(36, 'Oslo Energy Systems', 'Noruega', 'NOK', 30, 'Premium'),
(37, 'Lisbon Tech Hub', 'Portugal', 'EUR', 45, 'Estandar'),
(38, 'Prague Manufacturing', 'República Checa', 'CZK', 30, 'Estandar'),
(39, 'Vienna Precision', 'Austria', 'EUR', 45, 'Premium'),
(40, 'Jakarta Components', 'Indonesia', 'IDR', 30, 'Critico'),
(41, 'Manila Assembly', 'Filipinas', 'PHP', 45, 'Estandar'),
(42, 'Seattle Software', 'USA', 'USD', 15, 'Premium'),
(43, 'Frankfurt Parts', 'Alemania', 'EUR', 30, 'Estandar'),
(44, 'Beijing Smart City', 'China', 'CNY', 30, 'Premium'),
(45, 'Kyoto Robotics', 'Japón', 'JPY', 90, 'Premium'), -- Mucho crédito
(46, 'Johannesburg Tools', 'Sudáfrica', 'ZAR', 30, 'Critico'),
(47, 'Santiago Supply', 'Chile', 'CLP', 30, 'Estandar'),
(48, 'Bogota Logistics', 'Colombia', 'COP', 30, 'Estandar'),
(49, 'Quito Parts', 'Ecuador', 'USD', 15, 'Critico'),
(50, 'Lima Tech Store', 'Perú', 'PEN', 30, 'Estandar');

SELECT pais_origen, COUNT(*) as cantidad 
FROM dim_proveedores 
GROUP BY pais_origen 
ORDER BY cantidad DESC;
